language: python
python:
  - "2.7"
# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "pip install pyvenv pyvenv-virtualenv"
script: 
  - "source bootstrap.yml"
  - "python pbs/bin/main.py"
